language: node_js

node_js:
  - "7"
  - "6"

env: CXX=g++-5 CC=gcc-5
addons:
  apt:
    packages:
      - g++-5
    sources: &sources
      - ubuntu-toolchain-r-test

install:
  - npm install --build-from-source

script:
  - node test/mesh.js