dist: trusty
sudo: required
language: node_js

node_js:
  - "7"
  - "6"

env: CXX=clang++-3.8 CC=clang-3.8
addons:
  apt:
    packages:
      - clang-3.8
    sources: &sources
      - ubuntu-toolchain-r-test

install:
  - npm install --build-from-source

script:
  - node test/mesh.js